### ISSUE TITLE
bug: Docker image not found

### ISSUE THREAD

**Issue by yxliang01** [ChrisTimperley/Kaskara#53]
At https://github.com/ChrisTimperley/Kaskara/blob/76ee80dd3347dbd37e2f02cb9954f8f4f8ee996c/python/kaskara/project.py#L15 , it hard-coded the docker image that https://github.com/ChrisTimperley/Kaskara/blob/76ee80dd3347dbd37e2f02cb9954f8f4f8ee996c/python/kaskara/project.py#L48 would be creating a container from. Generally, for a fresh installation, image not found exception would be thrown.

#39 looks to be a tracking issue for fixing this.

**Comment by ChrisTimperley** [comment]
Fixed by `d02d36716505313a25460b6d6464b618a17769bd`
